name = "QuantizedArrays"
uuid = "a7db621c-8ce0-11e9-16a1-0f86dc86bd10"
authors = ["Corneliu Cofaru <cornel@oxoaresearch.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
